DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  address VARCHAR(250) DEFAULT NULL,
  city VARCHAR(250) DEFAULT NULL,
  country VARCHAR(250) DEFAULT NULL,
  email VARCHAR(250) DEFAULT NULL,
  image VARCHAR(250) DEFAULT NULL
);
